### ISSUE TITLE
No package 'dbus-1' found

### ISSUE THREAD

**Issue by Falieson** [chestm007/linux_thermaltake_riing#11]
**Describe the bug**
No package 'dbus-1' found

**To Reproduce**
1. sudo pip3 install linux_thermaltake_rgb

**Expected behavior**
succesfull install

**Stacktraces / logs**
```
  checking for DBUS... no
    configure: error: Package requirements (dbus-1 >= 1.8) were not met:
    
    No package 'dbus-1' found
    
    Consider adjusting the PKG_CONFIG_PATH environment variable if you
    installed software in a non-standard prefix.
    
    Alternatively, you may set the environment variables DBUS_CFLAGS
    and DBUS_LIBS to avoid the need to call pkg-config.
    See the pkg-config man page for more details.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jxcdxg60/dbus-python/setup.py", line 109, in <module>
        tests_require=['tap.py'],
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-jxcdxg60/dbus-python/setup.py", line 62, in run
        cwd=builddir)
      File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-build-jxcdxg60/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/usr/bin/python3', '--prefix=/tmp/pip-build-jxcdxg60/dbus-python/build/temp.linux-x86_64-3.6/prefix']' returned non-zero exit status 1.
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-jxcdxg60/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8nna_5y6-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-jxcdxg60/dbus-python/
```

**Desktop (please complete the following information):**
 - Ubuntu 18.10

**Comment by Falieson** [comment]
I've tried `sudo apt install -y libcairo2-dev` as suggested in a different repo with the same error, didn't fix the install script though

**Comment by chestm007** [comment]
The whole DBUS dependency is legacy code that is probably broken from a prerelease feature i implemented at the beginning of this project - its probably easier to just remove that.
I'll work on this shortly

**Comment by chestm007** [comment]
fixed in dc467caf1a150ee9eef04beffb6e1a85d3503690 pending release

**Comment by Falieson** [comment]
omg @chestm007 thanks so much for working on that so quickly for me!

**Comment by Falieson** [comment]
I saw on the pip site that you made a release on the 8th. I tried running the installer again (sorry not very familiar w/ pip) and received the same error.

```   configure: error: Package requirements (dbus-1 >= 1.8) were not met:
    
    No package 'dbus-1' found
    
    Consider adjusting the PKG_CONFIG_PATH environment variable if you
    installed software in a non-standard prefix.
    
    Alternatively, you may set the environment variables DBUS_CFLAGS
    and DBUS_LIBS to avoid the need to call pkg-config.
    See the pkg-config man page for more details.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-6hlkm1xq/dbus-python/setup.py", line 109, in <module>
```

**Comment by Falieson** [comment]
@chestm007 Could it be because of this line? https://github.com/chestm007/linux_thermaltake_riing/blob/beb828d2f4c6632dd41f77fec8a0d1812e6a622b/setup.py#L25

**Comment by chestm007** [comment]
:man_facepalming: not sure how i missed that... I'll fix it up

**Comment by chestm007** [comment]
adressed in commit c7433b60ba4ddc269e48f006d49c9fe096b09cc3 i believe

**Comment by Falieson** [comment]
installation went through! I think its worth noting that release 1.0 is feb 8, and these fixes can be installed with `sudo pip3 install linux-thermaltake-rgb==0.0.13.post1550523453`

**Comment by chestm007** [comment]
ugh, that looks entirely to do with the travis build, 0.0.13 and 0.1.0 were the same commit... that's frustrating

**Comment by chestm007** [comment]
closing as this versioning issue is made redundant with a newer release
