### ISSUE TITLE
Crash after "initializing AlternatingLightingEffect light controller"

### ISSUE THREAD

**Issue by illich** [chestm007/linux_thermaltake_riing#24]
Seems like a great software... but doesn't work for me :(

Short version:
After running linux-thermaltake-rgb it outputs:
initializing thermaltake rgb daemon
initializing AlternatingLightingEffect light controller
Traceback (most recent call last):
  File "./linux-thermaltake-rgb", line 11, in <module>
    load_entry_point('linux-thermaltake-rgb==0.2.0.post1555641151', 'console_scripts', 'linux-thermaltake-rgb')()
  File "/usr/local/lib/python3.6/dist-packages/linux_thermaltake_rgb/daemon/main.py", line 32, in main
    daemon = ThermaltakeDaemon()
  File "/usr/local/lib/python3.6/dist-packages/linux_thermaltake_rgb/daemon/daemon.py", line 44, in __init__
    self.lighting_manager = LightingEffect.factory(self.config.lighting_manager)
  File "/usr/local/lib/python3.6/dist-packages/linux_thermaltake_rgb/lighting_manager.py", line 75, in factory
    return subclass_dict.get(config.pop('model').lower())(config)
  File "/usr/local/lib/python3.6/dist-packages/linux_thermaltake_rgb/lighting_manager.py", line 140, in __init__
    self.odd_rgb = self.RGBMap(**self._config.get('odd_rgb'))
TypeError: type object argument after ** must be a mapping, not NoneType

Long version:
1. Have up-to-date Kubuntu 18.10.
2. Bought Riing 20 Plus and the controller, installed it, hardware works in default config (RGB and probably full fan speed).
3. Installed linux_thermaltake_riing according to README.
4. Launched the service, It does nothing.
5. Fixed the paths as described in issue #19.
6. Launched the service, It does nothing.
7. Tried to run it directly, it writes the traceback as above. That might be the main issue, although I'm not sure if it is supposed to work if run directly.

Questions
- What should I do to make it work?
- When run as a service, does it have some log, where I can see if it connects correctly?
- If I change something in the config, does it change immediatelly or do I need to restart the service?

**Comment by chestm007** [comment]
Thats interesting, can you send me the output of `lsusb -v` that should help me see if the controller is supported.

when ran as a service, the daemon should log to the journal under systemd, im unfortunately unsure on systems not using systemd.

config changes require a restart to reload the config.
